version: 2
plugins:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby

exclude_patterns:
  - bin/*
  - spec/**/*
  - examples/*.rb
  - README.md
  - README.ja.md
  - CHANGELOG.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - Gemfile
  - Gemfile.lock
