engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby

ratings:
  paths:
    - lib/**/*.rb

exclude_patterns:
  - bin/*
  - spec/**/*
  - examples/*.rb
